package features;

import utils.ConsoleColors;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;

public class ReportExporter {

    public static void exportDailyReport() {
        String filename = "DailyReport_" + LocalDate.now() + ".txt";

        int meals = MealManager.getMealCount();
        int calories = MealManager.getTotalCalories();
        int workouts = ExerciseManager.getWorkoutCount();
        int burned = ExerciseManager.getTotalBurnedCalories();
        double sleep = SleepTracker.getLastSleep();
        int water = WaterTracker.getWaterCount();

        try (FileWriter writer = new FileWriter(filename)) {
            writer.write("📋 DAILY HEALTH REPORT - " + LocalDate.now() + "\n");
            writer.write("🍽️ Meals: " + meals + "\n");
            writer.write("🔥 Calories Consumed: " + calories + " kcal\n");
            writer.write("🏋️ Workouts: " + workouts + "\n");
            writer.write("🔥 Calories Burned: " + burned + " kcal\n");
            writer.write("😴 Sleep: " + sleep + " hours\n");
            writer.write("💧 Water: " + water + " glasses\n");

            writer.write("✅ Generated by Savour the Flavours of Health\n");

            System.out.println(ConsoleColors.GREEN + "📄 Report exported to file: " + filename + ConsoleColors.RESET);

        } catch (IOException e) {
            System.out.println(ConsoleColors.RED + "❌ Failed to export report." + ConsoleColors.RESET);
        }
    }
}
